### ISSUE TITLE
Captcha bot is not working on discord

### ISSUE THREAD

**Issue by Calcifer1001** [bloxapp/ssv-network#127]
I'm posting this here, since there is no other place on discord to type this. This was originally posted on the gm channel on 10/30, and I commented the same thing today. When I click on the "verify" button, it only shows the following message

![image](https://user-images.githubusercontent.com/83971551/205754236-b1503354-18e7-4b22-b4a8-cd1aa56188ad.png)

**Comment by lior-blox** [comment]
@Calcifer1001 This is the contract repository, not related issue
